name: Test Sample

on:
  pull_request:

jobs:
  test:
    name: test-sample
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.11"
          check-latest: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest --benchmark-disable --cov
        continue-on-error: true

      - name: Run benchmark
        run: uv run pytest --timeout=0 --benchmark-only
